# Nome do Workflow
name: Aula 02 - Exemplo Completo de Push

# Gatilho (Trigger):
on:
  push:
    # Este é um exemplo mais completo que combina vários filtros para criar uma regra de execução robusta.
    # O workflow será acionado por um push se as condições de branch/tag E path forem atendidas.

    # CONDIÇÃO 1: O push deve ser para uma das seguintes branches OU tags.
    branches:
      - 'main'
      - 'feature/**'
    tags:
      - 'v*.*.*' # Aciona para tags de versão, ex: v1.0.0, v2.1.3

    # CONDIÇÃO 2: O workflow NÃO será acionado se TODAS as alterações no push
    # forem APENAS em arquivos ou diretórios listados abaixo.
    # Se uma alteração ocorrer em 'backend/app.js' E 'docs/README.md', o workflow irá rodar.
    # Se a alteração for APENAS em 'docs/README.md', o workflow será ignorado.
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  complex-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe informações do gatilho
        run: |
          echo "Workflow acionado por um evento de push."
          echo "Branch ou Tag: ${{ github.ref }}"
          echo "Este job roda em pushes para 'main'/'feature/**' ou tags 'v*.*.*', ignorando alterações que são apenas na documentação."